name: py
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo sandbox
        uses: actions/checkout@v2 
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5 
          cache: 'pip'
          
          
      - name: Install Dependencies
        run: pip install -r sandbox/requirements.txt
      
      - name: execute py script 
        run: |
          python sandbox/test.py
