name: Run the Python file

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #schedule:
  #  - cron: "05 6-18/2 * * *"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: europe-west3-docker.pkg.dev
  
jobs:
  run:
    name: run
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    permissions:
      contents: read
      id-token: write
      
    steps:
      - name: Docker Run Python
        # uses: kohlerdominik/docker-run-action@085f64350d397dfafb2e875961c6d44bedd3ee26
        uses: actions/setup-python@v2 #kohlerdominik/docker-run-action@v1.0.2
        with:
          python-version: '3.10'
          volumes: |
            ${{ github.workspace }}:/workspace
          workdir: /workspace
          run: |
            pip install -r requirements.txt
            python test.py
          # Available enviroment variables
          environment: |
            LC_ALL: de_DE.UTF-8
            LC_TIME: de_DE.UTF-8



      - name: Cleanup
        if: always()
        run: rm "${GOOGLE_APPLICATION_CREDENTIALS}" || true
