name: Run the Python file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #schedule:
  #  - cron: "05 6-18/2 * * *"
  
jobs:
  run:
    name: run
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    permissions:
      contents: read
      id-token: write
      
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: |
       python -VV
       pip install -r requirements.txt
       python test.py
    # Available enviroment variables
   #   environment: |
    #     LC_ALL: de_DE.UTF-8
    #     LC_TIME: de_DE.UTF-8
