name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run main py
      run: |
        python test.py

    - name: commit files
      run: |
        git config remote.origin.url https://github.com/Chesseling/sandbox.git
        git config --local user.email "der.hamburger@gmail.com"
        git config --local user.name "CHesseling"
        git add -A
        git commit -m "update data" -a
        
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  